openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
  description: API for managing tasks

paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/{id}:
    get:
      summary: Get a single task by ID
      parameters:
        - name: id
          in: path
          description: ID of the task
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        completed:
          type: boolean
      required:
        - id
        - title
        - completed

    ValidationError:
      type: object
      properties:
        error:
          type: string
        details:
          type: array
          items:
            type: string
      required:
        - error
        - details

    NotFoundError:
      type: object
      properties:
        error:
          type: string
      required:
        - error
